-- Group encryption keys: each member gets the group's shared key encrypted with their public key
-- The shared key is generated by the group creator and distributed to members
CREATE TABLE IF NOT EXISTS group_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    encrypted_key TEXT NOT NULL,  -- group key encrypted with member's X25519 public key
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(group_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_group_keys_group_id ON group_keys(group_id);
CREATE INDEX IF NOT EXISTS idx_group_keys_user_id ON group_keys(user_id);
